### PR TITLE
1.13 support

### PR DESCRIPTION
**Pull request by KennyTV**
As I'm currently a little too bored and heard a few people wining about this project being outdated, this exists :p
I didn't really reinvent the wheel, but did (start) the minimum required for 1.13 support.
It's also just a start to get input for needed changes as I am obviously not too familiar with the project.

It already compiles and starts on a 1.13 server , though I only tested a handful of commands such as give, kit, warps. I haven't yet touched or tested most config related things.

Legacy ids are no longer supported, also bumped the required Java version to 8
The things I am unsure about (more to come 👀):
* HelpComponent class -> VanillaCommand replaced or removed?
* We can't really test if items are damageable, so I'm just setting the durability to any item (shouldn't actually have any side effect on non-damageable items.. ?)
* Version specific stuff from the latest versions hasn't been added. One example are the note block sounds (JingleNote stuff)
* How to really handle config item entries (material names, WE item-/blocktypes with full names)

### CODE REVIEW

**Comment by DarkArc** [comment]
Thanks, hoping to look at this within the next week or so... Coincidentally I restored a very old server of mine (2014 era) which has heavy dependencies on CommandBook; in the coming months development/support might resume officially :)

**Comment by PikachuEXE** [comment]
Should I submit another PR for 1.14? (If I have time

**Comment by gp-Airee** [comment]
> Should I submit another PR for 1.14? (If I have time

Would be awesome.

**Comment by KennyTV** [comment]
Compiles fine with 1.14 as a dependency; it should be compatible without any changes

**Comment by gp-Airee** [comment]
> Compiles fine with 1.14 as a dependency; it should be compatible without any changes

Where can I build this? I can start testing and see if there's anything that needs to be fixed.

**Comment by KennyTV** [comment]
By cloning the fork (https://github.com/KennyTV/CommandBook) and building it with maven

**Comment by DarkArc** [comment]
Superseded by https://github.com/EngineHub/CommandBook/pull/116

**Pull request closed without merging**
